### ISSUE TITLE
version variable is hardcoded

### ISSUE THREAD

**Issue by Victor0118Tanaka** [Thomomys/Spherity-Code-Challenge#4]
version value is hardcoded
/api/v1/...
I think v1 should be defined in .env file

**Comment by black02430horse** [comment]
@Victor0118Tanaka 
Please leave an example so that @Thomomys can understand easily. (your suggestion??)

**Comment by Victor0118Tanaka** [comment]
![image](https://github.com/Thomomys/Spherity-Code-Challenge/assets/170364946/d1abe1dd-67b3-4463-a84c-2aa63b383546)

**Comment by Thomomys** [comment]
How about remove v1?

**Comment by Victor0118Tanaka** [comment]
v1 is useful for version management.
I think we are supposed to keep v1.

**Comment by Thomomys** [comment]
I will add this to .env.

# Api Version
VERSION=v1

**Comment by Victor0118Tanaka** [comment]
Nice!

**Comment by Thomomys** [comment]
Please revie this PR.
https://github.com/Thomomys/Spherity-Code-Challenge/pull/5
